# Generated by Django 2.0.7 on 2018-07-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_test',
            name='teble_name_Ja',
        ),
    ]
